name: Artifacts Demo
#artifacts allows us to share data betweenn jobs in a workflow
#and store data once that workflow has completed.

#there are some of the common artifacts  that we can upload.
#   Log files and core dump
#   Test results , failure, and screenshots.
#   stress test performance output and code coverage output.
on: push
jobs:
  job_2:
    runs-on: ubuntu-latest
    steps:
      - name: "creating file"
        run: echo "Hi this file is for writing purpose" > file.txt

      - uses: actions/upload-artifact@v2
        with:
          name: "uploading with uses" #this is the file name we should provide
          path: file.txt
  receiving_job:
    name: reseiving out from job 1
    runs-on: ubuntu-latest
    needs: job_2
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: "uploading with uses" #the names should be same
      - run: cat file.txt  