name: "Artifacts Demo"
#artifacts allows us to share data betweenn jobs in a workflow
#and store data once that workflow has completed.

#there are some of the common artifacts  that we can upload.
#   Log files and core dump
#   Test results , failure, and screenshots.
#   stress test performance output and code coverage output.
on:
  workflow-dispatch:
jobs:
  upload_job:
    runs-on: ubuntu-latest
    steps:
      name: creating file
      run: echo "Hi this file is for writing purpose" > file.txt

      uses: actions/upload-artifacts@v2
      with:
        name: uploading with uses
        path: file.txt
  receiving_job:
    name: reseiving out from job 1
    runs-on: ubuntu-latest
    steps:
      name: accessing the file from first job
      run: cat file.txt
      uses: actions/download-artfacts@v2

    