name: default_envs in evenry os.
on:
  workflow_dispatch:

jobs:
  windows_job:
    runs-on: windows-latest
    steps:
      - run: env
  linux_job:
     runs-on: ubuntu-latest
     steps:
      - run: env