name: default_envs in evenry os.
on:
  workflow_dispatch:

jobs:
  windows_job:
    runs-on: windows-latest
    steps:
      - run: env
  linux_job:
     runs-on: ubuntu-latest
     steps:
      - run: env
  secrate_variables:
    runs-on: ubuntu-latest
    steps:
    #i set this password in github-->settings.
      - run: echo 'SRISAI_PASSWORD:- ${{ secrets.SRISAI_PASSWORD}}'
      
      
        