name: using Environment rule are secret variables.
on:
  push:
  workflow_dispatch:
jobs:
  Env_job:
    runs-on: ubuntu-latest
    evironment:
      name: Env_protaction_rules
    steps:
      - name: 'Environment'
        run: echo ${{ secrets.SRISAI_PASSWORD}}