name: A  Basic work flow 
#Controls whn the workflow  will run 
on:
  push:
    branches: ["main"]
  pull_request:
    branches:  ["main"]
  #Allows you to run this workflow  manually from the actions tab.
  workflow_dispatch:

#workflow made upof one or more jobs that can run sequentially or in parallel.
jobs:
    #this workflow contains a single job called "build"
    build:
     #The type of runner that the job will run on.
      runs-on: ubuntu-latest

      #Steps  represent a sequence  of tasks that will be executed  as part of the job
      steps:
       # checks-out your repository under  $GITHUB_WORKSPACE, so your job can  access it
       - uses: actions/checkout@v3
       #runs a single command using the runners shell
       - name: Runs a one line script
         run: echo Hello world

       - name: Run a multiline script
         run: |
           echo and other actions too build
           echo test, and deploy your project
    build-api:
      runs-on: windows-latest
      steps: 
        - run: echo Windows run_3   
    build-api-app:
      need: build
      #build  job will run followed by "build-api-app" this is depends on the build job
      runs-on: windows-latest
      steps: 
        - run: echo Windows run
    packaging:
      needs: [build,build-api-app]
      runs-on: windows-latest
      steps:
        - run: echo Windows run_1
         
